# Request/goal: The amount of time that we want the turtle to move
int64 movement_duration
---
# Response/Result: Whether the turtle moved successfully or the action was interrupted 
bool result
---
# Feedback: progress of the action
int64 time_elapsed
